
name: Croner Python

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Ejecutar script de Python
      run: python ./croner.py
        
